version: 0.0.2-build{build}

image: Visual Studio 2017

platform:
  - x64

environment:
  matrix:
    - nodejs_version: 10
    - nodejs_version: 8
    - nodejs_version: 6


cache:
  - deps/usvfs -> .gitmodules
  - node_modules -> package.json

artifacts:
  - path: build/stage
  - type: zip
  - name: module

install:
  - ps: Install-Product node $env:nodejs_version $env:Platform
  - set BOOST_DIR=C:\Libraries\boost_1_67_0
  - IF /I "%PLATFORM%" == "x64" set BOOST_LIB=C:\Libraries\boost_1_67_0\lib64-msvc-14.1
  - IF /I "%PLATFORM%" == "x64" set PATH=C:\Python27-x64;%PATH%
  - IF /I "%PLATFORM%" == "x86" SET PATH=C:\python27;%PATH%
  - IF /I "%PLATFORM%" == "x86" SET BOOST_LIB=C:\Libraries\boost_1_67_0\lib32-msvc-14.1
  - npm config get
  - node -v
  - npm -v
  - node -e "console.log(process.arch);"
  - npm install
  - npm run package-binary

build: off
test: off
